### ISSUE TITLE
FAILED cache write. PermissionError(13, 'Permission denied')

### ISSUE THREAD

**Issue by masouduut94** [c0fec0de/anycache#2]
In windows I get this error anytime I want to use anycache

FAILED cache write 'D:\temp\37b7595b0ded284e7d7e2bc527d84ff8db9f2f5ae470a6eb2677371725cfdf41.cache'. PermissionError(13, 'Permission denied')

**Comment by Qazzquimby** [comment]
Same error regardless of cache location.

**Comment by c0fec0de** [comment]
It is a windows tmpfile problem.

**Comment by ghost** [comment]
Hmm, nice fix!
