### ISSUE TITLE
Option for Max Cache Age?

### ISSUE THREAD

**Issue by celestialorb** [c0fec0de/anycache#5]
I've been examining `anycache` today and it looks like the perfect solution to a problem I've been having with a small workflow script of mine. However I noticed there doesn't seem to be a way of controlling the maximum amount of time a cached result can live for. In my script I'd like for it to update the cache after it has lived for a certain amount of time (say, every week).

I did see that there's an `is_outdated` function, but that seems to be based on the source file returning `True` whenever the source file has been updated (which makes sense).

Could we get an option to specify `maxage` alongside `maxsize` for the cached results of a function? e.g.
```
import datetime

@anycache(cachedir="/path/to/cache", maxage=datetime.timedelta(weeks=1), maxsize=1000000)
def my_anycached_function():
  ...
```

Passing in `None` to the `maxage` parameter could disable the max age check.

**Comment by c0fec0de** [comment]
merged.
